name: HardCoreTest20250608
version: '1.0-SNAPSHOT'
main: magia.box.example.hardCoreTest20250608.HardCoreTest20250608
api-version: '1.21'
description: For custom Minecraft Mutiplayer Hardcore

commands:
  plo:

